version: '3'
services:
  mysql-test:
    image: mysql:5.7
    # image: mysql:latest
    # image: mysql:5.6
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234qwer.
      # command:
      # --default-authentication-plugin=mysql_native_password
      # --character-set-server=utf8mb4
      # --collation-server=utf8mb4_general_ci
      # --explicit_defaults_for_timestamp=true
      # --lower_case_table_names=1
      # --max_allowed_packet=128M;
    ports:
      - 3306:3306
  redis-test:
    image: redis:5
    container_name: redis-test
    command: redis-server --requirepass 123zxc
    #    volumes:
    #      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

